### ISSUE TITLE
kitchen fails with a strange help error after install kitchen-vagrant_winrm

### ISSUE THREAD

**Issue by devilldog** [criteo/kitchen-vagrant_winrm#11]
fresh install, added chef gem install kitchen-vagrant then chef gem install kitchen-vagrant_winrm 
I get the following error 
```lang
----> Starting Kitchen (v1.3.1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ShellOut::ShellCommandFailed
>>>>>> Message: Expected process to exit with [0], but received '1'
---- Begin output of vagrant winrm --plugin-version ----
STDOUT: Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.
STDERR: 
---- End output of vagrant winrm --plugin-version ----

```

**Comment by devilldog** [comment]
so I though hmm did not run bundle so I did that for kitchen-vagrant_winrm which works with out error but I get the same error when running kitchen test

**Comment by devilldog** [comment]
my bundle list and kitchen.yml

driver:
  name: vagrant
  usb: 'off'
  usbehci: 'off'

platforms:
  - name: mwrock/Windows2012R2
    driver:
      box: mwrock/Windows2012R2
      box_url: https://atlas.hashicorp.com/mwrock/boxes/Windows2012R2
    driver_plugin: vagrant_winrm
    driver_config:
      require_chef_omnibus: true
      guest: windows
      communicator: 'winrm'
      winrm_username: 'vagrant'
      winrm_password: 'vagrant'
    provisioner:
      name: chef_zero
      sudo: false
      root_path: /var/chef/
      chef_client_path: /opscode/chef/bin/chef-client
      chef_omnibus_root: /opscode/chef/
      ruby_bindir: /opscode/chef/embedded/bin


suites:
- name: tomcat7
  run_list: ["recipe[tomcat]"]
  attributes: {tomcat: {base_version: 7}}

Gems included by the bundle:
  * addressable (2.3.8)
  * berkshelf (3.2.3)
  * berkshelf-api-client (1.2.1)
  * buff-config (1.0.1)
  * buff-extensions (1.0.0)
  * buff-ignore (1.1.1)
  * buff-ruby_engine (0.1.0)
  * buff-shell_out (0.2.0)
  * bundler (1.7.12)
  * cane (2.6.2)
  * celluloid (0.16.0)
  * celluloid-io (0.16.2)
  * cleanroom (1.0.0)
  * countloc (0.4.0)
  * dep-selector-libgecode (1.0.2)
  * dep_selector (1.0.3)
  * diff-lcs (1.2.5)
  * erubis (2.7.0)
  * faraday (0.9.1)
  * ffi (1.9.8)
  * foodcritic (4.0.0)
  * gherkin (2.12.2)
  * hashie (2.1.2)
  * hitimes (1.2.2)
  * json (1.8.2)
  * kitchen-vagrant_winrm (0.3.0)
  * log_switch (0.3.0)
  * mini_portile (0.6.2)
  * minitar (0.5.4)
  * mixlib-authentication (1.3.0)
  * mixlib-log (1.6.0)
  * mixlib-shellout (2.0.1)
  * multi_json (1.11.0)
  * multipart-post (2.0.0)
  * net-http-persistent (2.9.4)
  * net-scp (1.2.1)
  * net-ssh (2.9.2)
  * nio4r (1.1.0)
  * nokogiri (1.6.6.2)
  * octokit (3.8.0)
  * parallel (1.4.1)
  * polyglot (0.3.5)
  * rake (10.4.2)
  * retryable (2.0.1)
  * ridley (4.1.2)
  * rspec (3.2.0)
  * rspec-core (3.2.3)
  * rspec-expectations (3.2.1)
  * rspec-mocks (3.2.1)
  * rspec-support (3.2.2)
  * rufus-lru (1.0.5)
  * safe_yaml (1.0.4)
  * sawyer (0.6.0)
  * semverse (1.2.1)
  * solve (1.2.1)
  * tailor (1.4.1)
  * term-ansicolor (1.3.0)
  * test-kitchen (1.3.1)
  * text-table (1.2.4)
  * thor (0.19.1)
  * timers (4.0.1)
  * tins (1.4.1)
  * treetop (1.6.2)
  * varia_model (0.4.0)
  * yajl-ruby (1.2.1)

**Comment by Annih** [comment]
Hello @devilldog 
It seems that you didn't install the vagrant plugin 'vagrant-winrm'.
Please run the following command:
```
vagrant plugin install vagrant-winrm
```
Let me know if you still encounter this issue.

**Comment by devilldog** [comment]
vagrant --version
Vagrant 1.7.2

and the plugin version works fine when i run it 
vagrant winrm --plugin-version
Vagrant-winrm plugin 0.7.0

**Comment by devilldog** [comment]
ok no idea how it is working now...no longer getting that error... strange...
