### ISSUE TITLE
Can this plugin be deprecated?

### ISSUE THREAD

**Issue by coderanger** [criteo/kitchen-vagrant_winrm#12]
With the release of Test Kitchen 1.4, Windows support was added to the core of Kitchen and the Vagrant plugin. Is this driver still needed? If not, can we mark it was deprecated and only needed for 1.3 and earlier?

**Comment by kamaradclimber** [comment]
yes we will deprecate this plugin as soon as we have migrated to kitchen 1.4

@annih, could you handle this?
